# Generated by Django 4.1.5 on 2024-06-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0005_remove_destination_name_remove_destination_weather_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='weather',
            new_name='Weather',
        ),
    ]
